name: Update README with Events

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Insert events into README
        run: |
          CONTENT=$(cat doc/events.md)
          awk -v content="$CONTENT" '
            /<!-- EVENTS_START -->/ {print; print content; inBlock=1; next}
            /<!-- EVENTS_END -->/ {inBlock=0}
            !inBlock' README.md > temp.md && mv temp.md README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest events" || exit 0
          git push
