name: Update README with Events

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract events content
        id: extract_events
        run: |
          CONTENT=$(cat doc/events.md)
          echo "events_content=$CONTENT" >> $GITHUB_ENV  # Use environment file

      - name: Update README
        id: update_readme
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            let readme = fs.readFileSync('./README.md', 'utf8');
            const eventsContent = process.env.events_content;

            const eventsHeading = '## Events';
            const eventsIndex = readme.indexOf(eventsHeading);

            if (eventsIndex === -1) {
              core.setFailed('## Events heading not found in README.md');
              return;
            }

            let nextHeadingIndex = readme.indexOf('## ', eventsIndex + eventsHeading.length);
            if (nextHeadingIndex === -1) {
              nextHeadingIndex = readme.length;
            }

            const newReadme = readme.substring(0, eventsIndex + eventsHeading.length) + '\n\n' + eventsContent + '\n' + readme.substring(nextHeadingIndex);

            fs.writeFileSync('./README.md', newReadme, 'utf8');

      - name: Commit and push changes
        uses: ad-m/github-push-action@master # Updated action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} # Push to the same branch
          force: false # Prevent push if no changes
